### ISSUE TITLE
Java Flow Control Topics To be Added

### ISSUE THREAD

**Issue by uiuxarghya** [javaistic/javaistic#102]
### These topics need to be added.
- [x] Java if...else #43 #87
- [x] Java switch Statement #88 
- [x] Java for Loop #142 
- [x] Java for-each Loop #266 
- [x] Java while Loop #373 
- [x] Java break Statement #579 
- [X] Java continue Statement #581 
- [X] Java switch Statement #88
