### ISSUE TITLE
Java Basic Programs

### ISSUE THREAD

**Issue by uiuxarghya** [javaistic/javaistic#201]
### Kind of Issue

Other

### Description

Adding java programs

- [x] Print An Integer #13 
- [x] Addition of two numbers #248 
- [x] Check Even or Odd Number #267 
- [x] Addition of two binary numbers #367
- [x] Add Two Complex Numbers #368 
- [x] Java Program to Multiply two Numbers #371 
- [x] Java Program to check Leap Year #561 
- [x] Java Program to check whether input character is vowel or consonant #743 
- [x] Java Program to calculate compound interest #570 
- [x] Java Program to calculate simple interest #564 
- [x] Java Program to find quotient and remainder #567 
- [x] Java Program to calculate power of a number #567 
- [ ] ....

### Contributing

Yes

**Comment by AbhishekJadhav2002** [comment]
Hello @uiuxarghya is this issue open for contributions ?
If yes, what is the requirements of the last task ?

**Comment by uiuxarghya** [comment]
> Hello @uiuxarghya is this issue open for contributions ? If yes, what is the requirements of the last task ?

Yes, this issue is open for collaboration.
I have updated the task list, the task is to add program docs for the given topics. 
> **Note**
> Program snippets written in docs must be written in Java

If you are ready to contribute then follow these simple steps:
1. fork this repo, 
2. make a new branch, 
3. - add your code [in the program's directory](https://github.com/javaistic/javaistic/tree/main/src/pages/programs), and 
   - update the [programs nav](https://github.com/javaistic/javaistic/blob/main/src/navs/program.js)
5. push your code, and 
6. open a pull request. 

> Go through the previous liked pull requests for a better understanding

**Comment by uiuxarghya** [comment]
> /assign

Hi @keshavMM004,
This issue is currently open for everyone. If you have a specific contribution in mind, feel free to mention it or raise a new issue with the details so we can better understand what you’d like to work on. Looking forward to your input!

**Comment by keshavMM004** [comment]
I want to fix this requirement - Java Program to check whether input character is vowel or consonant.

**Comment by uiuxarghya** [comment]
> I want to fix this requirement - Java Program to check whether input character is vowel or consonant.

Okay @keshavMM004, feel free to raise a pull request with the updated requirement. Would love to have your contribution!
